version: "3"

services:
  frontend-app:
    image: frontend-image
    ports:
      - "3000:3000"
    networks:
      - rickandmorty-app
  
  backend-app:
    image: backend-image
    ports:
      - "4000:4000"
    networks:
     - rickandmorty-app

networks:
  rickandmorty-app:
    driver: bridge